macvlans: fix a compile error due to docker 1.12.2
The error was:

    vendor/src/github.com/docker/libnetwork/drivers/macvlans/peerdb.go:332: not enough arguments in call to sbox.DeleteNeighbor
    vendor/src/github.com/docker/libnetwork/drivers/macvlans/peerdb.go:337: not enough arguments in call to sbox.DeleteNeighbor

Update peerdb.go to catch up with overlay:

    cp libnetwork/drivers/{overlay,macvlans}/peerdb.go